- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Global settings for memory logging.
    fortios_log_memory_global_setting:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: False
      log_memory_global_setting:
        full_final_warning_threshold: "80"
        full_first_warning_threshold: "50"
        full_second_warning_threshold: "70"
        max_size: "70000"
