- hosts: localhost
  gather_facts: false
  tasks:
  - fortios_firewall_policy:
      host: "192.168.122.40"
      username: admin
      password: ""
      vdom: root
      https: "False"
      ssl_verify: False
      state: "present"
      firewall_policy:
        policyid: "2002"
        name: "Policy_2002"
        action: "deny"
        srcintf:
          - name: any
        dstintf:
          - name: any
        srcaddr: 
          - name: 'all'
        dstaddr:
          - name: 'all'
        service: 
          - name: 'HTTP'
          - name: 'HTTPS'
        schedule: "always"
        logtraffic: "all"
        logtraffic_start: "disable"


