- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Create a DLP fingerprint database by allowing the FortiGate to access a file server containing files from which to create fingerprints.
    fortios_dlp_fp_doc_source:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: False
      state: "present"
      dlp_fp_doc_source:
        date: "3"
        file_path: "/usr/local/dlp"
        file_pattern: "*"
        keep_modified: "enable"
        name: "dlp_fp_server"
        password: "pw1"
        period: "none"
        remove_deleted: "enable"
        scan_subdirectories: "enable"
        sensitivity: "Warning"
        server: "192.168.100.40"
        username: "myuser"
