- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPS custom signature.
    fortios_ips_custom:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: False
      state: "present"
      ips_custom:
        action: "pass"
        application: "Other"
        comment: "Comment."
        location: "client"
        log: "disable"
        log_packet: "disable"
        os: "Linux"
        protocol: "TCP"
        severity: "info"
        signature: "F-SBID( --name 'Block.example.com'; --pattern 'example.com'; --service HTTP; --no_case; --flow from_client; --context host; )"
        status: "disable"
        tag: "ipsSignature"
