- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Settings for local disk logging.
    fortios_log_disk_setting:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      log_disk_setting:
        diskfull: "overwrite"
        dlp-archive-quota: "4"
        full-first-warning-threshold: "50"
        full-second-warning-threshold: "80"
        full-final-warning-threshold: "90"
        ips-archive: "enable"
        log-quota: "9"
        max-log-file-size: "10"
        max-policy-packet-capture-size: "11"
        maximum-log-age: "12"
        report-quota: "13"
        roll-schedule: "daily"
        roll-time: "14:30"
        source-ip: "192.168.122.40"
        status: "enable"
        upload: "enable"
        upload-delete-files: "enable"
        upload-destination: "ftp-server"
        uploaddir: "/"
        uploadip: "10.2.4.10"
        uploadpass: "pw123"
        uploadport: "8025"
        uploadsched: "disable"
        uploadtime: "14:00"
        uploadtype: "traffic"
        uploaduser: "myuser"
