- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Extender controller configuration.
    fortios_extender_controller_extender:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: False
      state: "present"
      extender_controller_extender:
        aaa_shared_secret: "aaa-sh"
        access_point_name: "ap1"
        admin: "disable"
        billing_start_day: "7"
        dial_mode: "dial-on-demand"
        dial_status: "14"
        id:  "17"
        quota_limit_mb: "29"
        redial: "1"
        roaming: "enable"
        role: "none"
        sim_pin: "1324"
        vdom: "1"
        wimax_auth_protocol: "tls"
