- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPv6 to IPv4 policies.
    fortios_firewall_policy64:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: False
      state: "present"
      firewall_policy64:
        policyid: 1
        srcintf: port1
        dstintf: port1
        srcaddr:
        - name: all
        dstaddr:
        - name: all
        action: accept
        status: enable
        schedule: always
        service:
        - name: ALL
        logtraffic: disable
        permit_any_host: disable
        traffic_shaper: ''
        traffic_shaper_reverse: ''
        per_ip_shaper: ''
        fixedport: disable
        ippool: disable
        poolname: []
        tcp_mss_sender: 0
        tcp_mss_receiver: 0
        comments: ''
