- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPv6 to IPv4 virtual IPs.
    fortios_firewall_vip64:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_vip64:
        state: "present"
        name: myVip64
        comment: new
        type: static_nat
        src_filter: []
        extip: "::1939:a823:3c9d-::1939:a823:3c9f"
        mappedip: 10.23.104.10-10.23.104.12
        arp_reply: enable
        portforward: enable
        protocol: tcp
        extport: 250-260
        mappedport: 8250-8260
        color: 0
        ldb_method: static
  - name: Configure IPv6 to IPv4 virtual IP groups.
    fortios_firewall_vipgrp64:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_vipgrp64:
        state: "present"
        color: "3"
        comments: "Simple vip group 64"
        member:
         -
            name: "myVip64"
        name: "My vip group 64"
