- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure DNS translation.
    fortios_firewall_dnstranslation:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_dnstranslation:
        dst: "10.20.10.40"
        id:  "4"
        netmask: "255.255.255.0"
        src: "10.43.11.32"
