- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Filters for FortiCloud.
    fortios_log_fortiguard_filter:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      log_fortiguard_filter:
        anomaly: "enable"
        dlp_archive: "enable"
        dns: "enable"
        filter: ""
        filter_type: "include"
        forward_traffic: "enable"
        gtp: "enable"
        local_traffic: "enable"
        multicast_traffic: "enable"
        severity: "information"
        sniffer_traffic: "enable"
        ssh: "enable"
        voip: "enable"
