- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure FortiClient Enterprise Management Server (EMS) entries.
    fortios_endpoint_control_forticlient_ems:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: False
      state: "present"
      endpoint_control_forticlient_ems:
        address: "update.microsoft.com"
        admin_password: "pw"
        admin_type: "Windows"
        admin_username: "admin"
        https_port: "7"
        listen_port: "8"
        name: "myEMS"
        rest_api_auth: "disable"
        serial_number: "FCTEMS1231231231"
        upload_port: "12"
