- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure protocol options.
    fortios_firewall_profile_protocol_options:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_profile_protocol_options:
        state: "present"
        comment: "Optional comments."
        http:
            block_page_status_code: "101"
            comfort_amount: "20"
            comfort_interval: "21"
            http_policy: "disable"
            inspect_all: "enable"
            options: "clientcomfort"
            oversize_limit: "27"
            post_lang: "jisx0201"
            range_block: "disable"
            retry_count: "31"
            scan_bzip2: "enable"
            status: "enable"
            streaming_content_bypass: "enable"
            strip_x_forwarded_for: "disable"
            switching_protocols: "bypass"
            uncompressed_nest_limit: "37"
            uncompressed_oversize_limit: "38"
        ftp:
            ports: "21"
            options: "splice"
        imap:
            ports: "143"
            options: "fragmail"
        mapi:
            ports: "135"
            options: "fragmail"
        pop3:
            ports: "110"
            options: "fragmail"
        smtp:
            ports: "25"
            options: "fragmail"
        nntp:
            ports: "119"
            options: "splice"
        dns:
            ports: "53"
        name: "fw_prof_protocol1"
