- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPS sensor.
    fortios_ips_sensor:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      ips_sensor:
        name: default2
        comment: Prevent critical attacks.
        replacemsg_group: ''
        block_malicious_url: disable
        extended_log: disable
        entries:
        - id: 1
          rule: []
          location: all
          severity: 'medium high critical '
          protocol: all
          os: all
          application: all
          status: default
          log: enable
          log_packet: disable
          log_attack_context: disable
          action: default
          rate_count: 0
          rate_duration: 60
          rate_mode: continuous
          rate_track: none
          exempt_ip: []
          quarantine: none
          quarantine_expiry: 5m
          quarantine_log: enable
        filter: []
        override: []
